-- 3월에 태어난 여성 회원 목록 출력하기

-- 집계할 일이 없으면 GROUP BY HAVING 쓰지 말고 WHERE절에서 처리

SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH) = 3 AND GENDER = 'W' AND TLNO IS NOT NULL
ORDER BY MEMBER_ID;
