-- 오프라인/온라인 판매 데이터 통합하기

SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, 
SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE LIKE '2022-03%'
UNION ALL
-- UNION ALL로 PK FK 관계 없는거 합칠 수 있음
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID,
CASE WHEN 
OFFLINE_SALE_ID IS NOT NULL THEN NULL
END AS USER_ID, SALES_AMOUNT
-- 나는 CASE WHEN 썼는데 UNION ALL의 경우에는 첫번째 테이블과 똑같이 가져가므로 그냥 NULL이라고만 써도 가능 관련 SQL은 하단에 주석으로 표시
FROM OFFLINE_SALE 
WHERE SALES_DATE LIKE '2022-03%'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;

-- SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, 
-- SALES_AMOUNT
-- FROM ONLINE_SALE
-- WHERE SALES_DATE LIKE '2022-03%'
-- UNION ALL
-- SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT 
-- FROM OFFLINE_SALE 
-- WHERE SALES_DATE LIKE '2022-03%'
-- ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;