-- SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d')#Y는 4자리, m는 두자리, d는 두자리
-- FROM BOOK
-- WHERE PUBLISHED_DATE LIKE '2021%' AND CATEGORY LIKE '인문'
-- ORDER BY PUBLISHED_DATE

SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d')#Y는 4자리, m는 두자리, d는 두자리
FROM BOOK
WHERE YEAR(PUBLISHED_DATE) = 2021 AND CATEGORY LIKE '인문'
ORDER BY PUBLISHED_DATE