SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FNI
ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE (FI.FISH_TYPE, FI.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH) FROM FISH_INFO GROUP BY FISH_TYPE)
ORDER BY FI.ID;

--서브 쿼리에서 MAX(LENGTH) 값만 조사해버리면은 다른 물고기 타입 최대값과의 혼선이 있을 수 있기에
-- 두가지 컬럼으로 IN 비교하기