SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR, 
((SELECT MAX(LE.SIZE_OF_COLONY) FROM ECOLI_DATA LE WHERE YEAR = YEAR(LE.DIFFERENTIATION_DATE)) - E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
FROM ECOLI_DATA AS E
ORDER BY YEAR, YEAR_DEV;