SELECT CAR_ID, 
CASE WHEN CAR_ID IN (
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE) THEN '대여중'
ELSE '대여 가능' END AS AVAILABILITY    
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;

-- case when으로 갈 때 같은 CAR_ID더라도 시간대에 따라서 될 수도 있고 안될수도 있기 때문에 그런거 고려해서 작성하고,
-- 이후에 CAR_ID 값에는 중복도 허용해서 뽑은 값이기에 GROUP BY로 묶어서 중복 제거해버리기
