SELECT B.BOOK_ID, A.AUTHOR_NAME, 
TO_CHAR(B.PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
FROM BOOK B, AUTHOR A
WHERE B.AUTHOR_ID = A.AUTHOR_ID AND B.CATEGORY = "경제"
ORDER BY PUBLISHED_DATE ASC;

-- mysql의 dateformat 형태를 쓰고 싶으면 TO_CHAR 쓰고 년월 쓸 때는 풀네임으로 적기