-- SELECT O.ANIMAL_ID, O.NAME
-- FROM ANIMAL_OUTS AS O
-- LEFT JOIN ANIMAL_INS AS I
-- ON I.ANIMAL_ID = O.ANIMAL_ID
-- WHERE I.ANIMAL_ID IS NULL
-- ORDER BY O.ANIMAL_ID

SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O, ANIMAL_INS I
WHERE O.ANIMAL_ID = I.ANIMAL_ID(+) AND I.ANIMAL_ID IS NULL
ORDER BY O.ANIMAL_ID;

-- left join 걸고 없는 값들에 한해서 null 처리 되어있는거를 잘 가공하면 됨(+) 주의하기