--그룹별 조건에 맞는 식당 목록 출력하기
--GROUP BY로 집계한거 ORDER BY에서 COUNT로 활용해서 LIMIT 걸어서 뽑아내기
SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN REST_REVIEW R
ON P.MEMBER_ID = R.MEMBER_ID
WHERE R.MEMBER_ID = (SELECT MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID ORDER BY COUNT(*) DESC LIMIT 1)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;


