SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM((P.PRICE * O.AMOUNT)) AS TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY P.PRODICT_ID, P.PRODUCT_NAME
--원칙적으로 묶음 함수(SUM 등)를 쓰지 않은 일반 컬럼은 전부 다 GROUP BY에 똑같이 적어주어야 데이터베이스가 헷갈려하지 않고 에러를 내지 않습니다.
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID;