--재구매가 일어난 상품과 회원 리스트 구하기
SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
WHERE (USER_ID, PRODUCT_ID) IN
(SELECT USER_ID, PRODUCT_ID FROM ONLINE_SALE 
 GROUP BY USER_ID, PRODUCT_ID
 HAVING COUNT(*) > 1
)
GROUP BY USER_ID, PRODUCT_ID
ORDER BY USER_ID, PRODUCT_ID DESC;

--얘를 굳이 count 서브쿼리 쓰지말고 group by 처음한거에서 count 뽑아내도됨
SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(*) > 1
ORDER BY USER_ID, PRODUCT_ID DESC;