WITH F AS(
SELECT B.ID # B가 자식이고 A가 부모임
FROM ECOLI_DATA A
JOIN ECOLI_DATA B
ON A.ID = B.PARENT_ID
WHERE A.PARENT_ID IS NULL)

SELECT C.ID
FROM ECOLI_DATA C
JOIN F
ON C.PARENT_ID = F.ID
ORDER BY C.ID;
--서브쿼리로 1차적으로 뽑아내고 그거랑 조인걸어서 2세대 찾아내는 방법