WITH MX_EC AS (
SELECT YEAR(DIFFERENTIATION_DATE) AS MX_YEAR,
    MAX(SIZE_OF_COLONY) AS MX_COL
FROM ECOLI_DATA 
GROUP BY YEAR(DIFFERENTIATION_DATE))

-- SELECT 
-- YEAR(A.DIFFERENTIATION_DATE) AS YEAR,
-- ((SELECT MX_COL FROM MX_EC WHERE YEAR = MX_YEAR)-A.SIZE_OF_COLONY) AS YEAR_DEV,
-- A.ID
-- FROM ECOLI_DATA AS A
-- ORDER BY YEAR, YEAR_DEV;

SELECT 
YEAR(A.DIFFERENTIATION_DATE) AS YEAR,
(B.MX_COL - A.SIZE_OF_COLONY) AS YEAR_DEV,
A.ID
FROM ECOLI_DATA AS A
JOIN MX_EC B
ON YEAR(A.DIFFERENTIATION_DATE) = B.MX_YEAR
ORDER BY YEAR, YEAR_DEV;